version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-init:/cassandra-init
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 20

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: outputdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-producer:
    image: python:3.11-slim
    container_name: kafka-producer
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_started
    working_dir: /app
    volumes:
      - ./scripts:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: outputdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: tracking
    command: >
      bash -lc "pip install --no-cache-dir kafka-python mysql-connector-python pandas &&
      python /app/fake-data.py"

  kafka-consumer:
    image: python:3.11-slim
    container_name: kafka-consumer
    depends_on:
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_started
    working_dir: /app
    volumes:
      - ./scripts:/app
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_KEYSPACE: logs
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: tracking
    command: >
      bash -lc "pip install --no-cache-dir kafka-python cassandra-driver &&
      python /app/kafka_to_cassandra.py"

  spark:
    build: ./spark
    container_name: spark
    depends_on:
      cassandra:
        condition: service_healthy
      mysql:
        condition: service_started
    volumes:
      - ./data:/app/data
    command: ["spark-submit", "--master", "local[*]", "/app/main.py"]

volumes:
  cassandra_data:
    external: true
    name: 505d225888054c0b06df215230a6cbea47e868b125e8ccc2fd7d12a78361630a
    
  mysql_data:
    external: true
    name: e23f658a0b30750b0bb648610bb4f3cb30cff99edfaf65e7f1e38e85536a2d37